/*
 * Copyright 2018 DrJavaSaurus <javasaurusdev@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jmonkey2D.control;

import com.simsilica.es.base.DefaultEntityData;
import jmonkey2D.model.GameObject;

/**
 *
 * @author DrJavaSaurus <javasaurusdev@gmail.com>
 */
public class GameObjectPool extends DefaultEntityData {

    public GameObjectPool() {

    }

    /**
     * Creates a new game object
     *
     * @return a fresh gameobject (including an entityId generated by this pool)
     */
    public GameObject CreateGameObject() {
        return new GameObject(this);
    }

}
